---
title: "Gov 50 Final Project"
author: "James McAffrey"
description: "Education Data"
output:
  distill::distill_article:
    self_contained: false
---


## Project Data Proposal

Does public distrust lead to more civic engagement? In this study, I plan to examine the levels of distrust in American government since the 1960s to see if higher distrust in government causes greater turnout rates during presidential/congressional elections. I hypothesize that voter turnout will resemble an upside bell curve, where as trust is highest in the government, there is a higher level of engagement, and when trust is lowest in the government, there is also a higher turnout. The low point of turn out will be when trust is in the middle. This is because I believe there is a probable correlation of government successes and failures with the level of trust in government. I believe that when people feel the government is doing a good job and they are excited about their elected official, they will want to go to the polls to be part of their success. On the flip side, I believe when a public official is doing an incredibly poor job, people are generally a bit outraged and are more likely to go to the polls. The lowest moments for voting numbers will be when a public official is doing a fine job, not doing anything special but also not outragously offending anybody. My hypothesis would be supported if the times of high distrust or high trust are the same times as higher voter turnout and if the times of median distrust/trust are the times of low voter turnout. My hypothesis would be disproven if there was a linear relation between trust and voter turnout. 









